version: '3'

services:

  auth-system:
    build: .
    env_file: 
      - .env
    ports: 
      - 8000:8000
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    restart: always
    env_file:
      - .env
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080