version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: auth-system
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080